#!/usr/bin/env bash
#print out domain and subdomain

domain-dis ()
{
	domain = "$1"
	subdomain = "$2"
	"dig "%s"."%s" | awk '/ANSWER:/{getline; printf "The subdomain %s is a %s record and points to %s\n, var, $4, $5}' var="%s"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "%s" ] ;
	then
		domain-dis "$1" "%s"
	fi
done
