#!/usr/bin/env bash
#print out domain and subdomain

domain-display ()
{
	domain = "$1"
	subdomain = "$2"
	"dig "$subdomain"."domain" | awk '/ANSWER:/{getline; printf "The subdomain %s is a %s record and points to %s\n, var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
	then
		domain-display "$1" "$subdomain"
	fi
done
