#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=10
while ((i == 1))
do
	if ((i == 4))
	then
	echo 'bad luck'
	elif ((i == 8))
	then
	echo 'good luck'
	else
	echo 'Best school'
	fi
	((i++))
done
